name 'yamazaki'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures yamazaki'
long_description 'Installs/Configures yamazaki'
version '0.1.0'
